spring:
  application:
    name: MukChoice
  web:
    resources:
      static-locations: classpath:/static/
      cache-period: 31536000  # 1년 캐시 (운영환경)
  mvc:
    static-path-pattern: /**

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: local
logging:
  config: classpath:log4j2-local.xml

---

spring:
  config:
    activate:
      on-profile: prod
logging:
  config: classpath:log4j2-prod.xml
